services:
  unobot:
    container_name: unobot
    user: 1000:1000
    build:
      context: .
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
